import PDFDocument from "pdfkit";
import {
  addBrandHeader,
  addFooter,
  colors,
  drawKeyValueGrid,
  drawStatusBadge,
  formatCurrency,
  formatDate
} from "./pdfTheme.js";

export const createInvoicePdf = (payment) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4" });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    addBrandHeader(doc, {
      title: "Payment Receipt",
      subtitle: "Premium payment invoice for policy billing, transaction tracking, and customer records.",
      badge: payment.status || "payment"
    });

    drawStatusBadge(
      doc,
      payment.status,
      doc.page.width - 148,
      doc.y - 4,
      payment.status === "paid" ? "success" : payment.status === "pending" ? "warning" : "danger"
    );

    doc.roundedRect(48, doc.y + 8, doc.page.width - 96, 86, 12).fill(colors.primary);
    doc.fontSize(10).fillColor("#ddd6fe").text("AMOUNT PAID", 70, doc.y + 28);
    doc.fontSize(28).fillColor("#ffffff").text(formatCurrency(payment.amount), 70, doc.y + 44);
    doc.y += 112;

    doc.fontSize(14).fillColor(colors.ink).text("Transaction Details", 48, doc.y);
    doc.moveDown(0.8);

    drawKeyValueGrid(doc, [
      { label: "Invoice Number", value: payment.paymentNumber },
      { label: "Payment Date", value: formatDate(payment.paymentDate) },
      { label: "Customer", value: payment.customer?.fullName || "N/A" },
      { label: "Policy Number", value: payment.policy?.policyNumber || "N/A" },
      { label: "Method", value: payment.method },
      { label: "Transaction ID", value: payment.transactionId || "N/A" }
    ]);

    doc.moveDown(0.6);
    doc.roundedRect(48, doc.y, doc.page.width - 96, 72, 10).fillAndStroke("#ecfeff", "#bae6fd");
    doc.fontSize(11).fillColor(colors.secondary).text("Billing Note", 64, doc.y + 15);
    doc
      .fontSize(10)
      .fillColor(colors.muted)
      .text("Keep this receipt for renewal, claim, and audit verification. This document is generated by the system.", 64, doc.y + 34, {
        width: doc.page.width - 128
      });

    addFooter(doc);

    doc.end();
  });
