import PDFDocument from "pdfkit";

const formatCurrency = (amount = 0) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  }).format(amount);

export const createInvoicePdf = (payment) =>
  new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.fontSize(22).text("Insurance Payment Invoice", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Invoice Number: ${payment.paymentNumber}`);
    doc.text(`Payment Date: ${new Date(payment.paymentDate).toLocaleDateString()}`);
    doc.text(`Status: ${payment.status}`);
    doc.moveDown();
    doc.text(`Customer: ${payment.customer?.fullName || "N/A"}`);
    doc.text(`Policy Number: ${payment.policy?.policyNumber || "N/A"}`);
    doc.text(`Method: ${payment.method}`);
    doc.text(`Transaction ID: ${payment.transactionId || "N/A"}`);
    doc.moveDown();
    doc.fontSize(14).text(`Amount Paid: ${formatCurrency(payment.amount)}`);
    doc.moveDown();
    doc.fontSize(10).fillColor("#64748b").text("Generated by Insurance Management System");

    doc.end();
  });
