export const colors = {
  ink: "#111827",
  muted: "#64748b",
  line: "#e2e8f0",
  panel: "#f8fafc",
  primary: "#6d28d9",
  secondary: "#0f766e",
  accent: "#2563eb",
  success: "#059669",
  warning: "#d97706",
  danger: "#dc2626",
  dark: "#160b35"
};

export const formatCurrency = (amount = 0) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  }).format(amount);

export const formatDate = (date) => {
  if (!date) return "N/A";
  return new Date(date).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric"
  });
};

export const addBrandHeader = (doc, { title, subtitle, badge }) => {
  const pageWidth = doc.page.width;
  const x = 36;
  const y = 34;
  const width = pageWidth - 72;

  doc.save();
  doc.roundedRect(x, y, width, 112, 14).fill(colors.dark);
  doc.circle(x + width - 58, y + 34, 86).fillOpacity(0.18).fill("#8b5cf6");
  doc.circle(x + width - 118, y + 96, 62).fillOpacity(0.15).fill("#06b6d4");
  doc.fillOpacity(1);

  doc
    .fontSize(10)
    .fillColor("#c4b5fd")
    .text("AUTOSURE INSURANCE", x + 24, y + 22, { characterSpacing: 1.2 });
  doc.fontSize(24).fillColor("#ffffff").text(title, x + 24, y + 42, { width: width - 190 });
  doc.fontSize(10).fillColor("#dbeafe").text(subtitle, x + 24, y + 78, { width: width - 190 });

  if (badge) {
    doc.roundedRect(x + width - 154, y + 24, 116, 34, 17).fillOpacity(0.18).fill("#ffffff");
    doc.fillOpacity(1).fontSize(10).fillColor("#ffffff").text(badge, x + width - 140, y + 35, {
      width: 88,
      align: "center"
    });
  }
  doc.restore();

  doc.y = y + 138;
};

export const addFooter = (doc) => {
  const y = doc.page.height - 48;
  doc
    .moveTo(36, y - 12)
    .lineTo(doc.page.width - 36, y - 12)
    .strokeColor(colors.line)
    .stroke();
  doc
    .fontSize(8)
    .fillColor(colors.muted)
    .text("Generated by DriveSure", 36, y, {
      width: doc.page.width - 72,
      align: "center"
    });
};

export const drawKeyValueGrid = (doc, items, options = {}) => {
  const startX = options.x || 48;
  const startY = options.y || doc.y;
  const colWidth = options.colWidth || 245;
  const rowHeight = options.rowHeight || 54;
  const gap = options.gap || 14;

  items.forEach((item, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = startX + col * (colWidth + gap);
    const y = startY + row * (rowHeight + gap);

    doc.roundedRect(x, y, colWidth, rowHeight, 8).fillAndStroke(colors.panel, colors.line);
    doc.fontSize(8).fillColor(colors.muted).text(item.label.toUpperCase(), x + 14, y + 11, {
      width: colWidth - 28
    });
    doc.fontSize(12).fillColor(colors.ink).text(String(item.value || "N/A"), x + 14, y + 27, {
      width: colWidth - 28
    });
  });

  doc.y = startY + Math.ceil(items.length / 2) * (rowHeight + gap) + 4;
};

export const drawStatusBadge = (doc, text, x, y, tone = "primary") => {
  const toneMap = {
    success: colors.success,
    warning: colors.warning,
    danger: colors.danger,
    primary: colors.primary
  };
  const fill = toneMap[tone] || colors.primary;

  doc.roundedRect(x, y, 94, 24, 12).fill(fill);
  doc.fontSize(9).fillColor("#ffffff").text(String(text || "N/A").toUpperCase(), x + 8, y + 8, {
    width: 78,
    align: "center"
  });
};
